export const focusCopy = {
  dialogLabel: 'Focus mode',
  untilBreak: 'Until break',
  timeWorked: 'Time worked',
  pause: 'Pause',
  resume: 'Resume',
  stop: 'Stop',
  leave: 'Leave',
  stayOnList: 'Stay on list next time',
  openOnStart: 'Open focus when I start',
  durationLabel: 'Session length',
  minutes: (n) => `${n}m`,
  customMinutes: 'Custom',
  customPlaceholder: 'Minutes',
  applyCustom: 'Set',
  sessionEndedTitle: 'Break time',
  sessionEndedBody:
    'Your focus block ended. Pause or stop the timer when you’re done.',
  smileHint: 'Smile once. Soften the shoulders. Then keep going.',
}
